apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-explorer
  labels:
    app: redis-explorer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: redis-explorer.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: redis-explorer
            port:
              number: 3000
