apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-explorer-data
  labels:
    app: redis-explorer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
