apiVersion: v1
kind: Service
metadata:
  name: redis-explorer
  labels:
    app: redis-explorer
spec:
  type: NodePort
  selector:
    app: redis-explorer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
